// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/hadiyanfathur/golang-movies/app"
	"github.com/hadiyanfathur/golang-movies/controller"
	"github.com/hadiyanfathur/golang-movies/repository"
	"github.com/hadiyanfathur/golang-movies/service"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	movieRepositoryImpl := repository.NewMovieRepositoryImpl()
	db := app.InitDB()
	validate := validator.New()
	movieServiceImpl := service.NewMovieService(movieRepositoryImpl, db, validate)
	movieControllerImpl := controller.NewMovieController(movieServiceImpl)
	router := app.NewRouter(movieControllerImpl)
	server := NewServer(router)
	return server
}

// injector.go:

var movieSet = wire.NewSet(repository.NewMovieRepositoryImpl, wire.Bind(new(repository.MovieRepository), new(*repository.MovieRepositoryImpl)), service.NewMovieService, wire.Bind(new(service.MovieService), new(*service.MovieServiceImpl)), controller.NewMovieController, wire.Bind(new(controller.MovieController), new(*controller.MovieControllerImpl)))
